"""rename_age_to_date_of_birth

Revision ID: 99b50d844a9e
Revises: 001_full_schema
Create Date: 2026-04-28 12:15:36.348249
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b50d844a9e'
down_revision: Union[str, None] = '001_full_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
